kalahi_cidss/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.sign_in, name='login'),
    path('logout/', views.sign_out, name='logout'),
]

kalahi_cidss/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.access_data, name='dashboard'),
]

kalahi_cidss/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

kalahi_cidss/kalahi_cidss/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='login')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
] 
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kalahi_cidss/kalahi_cidss/templates/base.html
<!-- base.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <script src="{% static 'javascript/base.js' %}"></script>
    {% block staticfiles %}
    {% endblock %}
</head>
<body>
    <nav>
        <div class="navbar-logo">
            <img class="logo" src="{% static 'images/base/dswd_logo.png' %}" alt="KALAHI-CIDSS Logo">
        </div>
        <div class="navbar-list">
            <ul class="navbar">
                <li>
                    <a href="{% url 'dashboard:dashboard' %}">
                        <img class="icon" id="dashboard-icon" src="{% static 'images/base/dashboard.svg' %}"
                            alt="Dashboard Icon">
                    </a>
                </li>
                <li>
                    <img class="icon" id="account-icon" src="{% static 'images/base/account.svg' %}" alt="Account Icon">
                    <ul class="account-menu">
                        <li>
                            <img class="account-menu-icon" id="account-icon"
                                src="{% static 'images/account/account_user.svg' %}" alt="User Icon">
                            <a href="{% url 'home:home' %}">
                                Account
                            </a>
                        </li>
                        <li>
                            <img class="account-menu-icon" id="account-icon"
                                src="{% static 'images/account/logout.svg' %}" alt="User Icon">
                            <a href="{% url 'account:logout' %}">
                                Logout
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <aside>
        <ul class="sidebar">
            <li>
                <a href="{% url 'home:home' %}">
                    <img class="sidebar-menu-icon" id="sidebar-icon" src="{% static 'images/base/home.svg' %}" alt="Home Icon">
                    Home
                </a>
            </li>
            <li>
                <a href="{% url 'dashboard:dashboard' %}">
                    <img class="sidebar-menu-icon" id="sidebar-icon" src="{% static 'images/base/dashboard.svg' %}" alt="Dashboard Icon">
                    Dashboard
                </a>
            </li>
            <li>
                <a href="{% url 'home:home' %}">
                    <img class="sidebar-menu-icon" id="sidebar-icon" src="{% static 'images/base/account.svg' %}" alt="Account Icon">
                    Account
                </a>
            </li>
            <li>
                <a href="{% url 'account:logout' %}">
                    <img class="sidebar-menu-icon" id="sidebar-icon" src="{% static 'images/base/logout.svg' %}" alt="Logout Icon">
                    Logout
                </a>
            </li>
        </ul>
    </aside>
    <div class="overlay"></div>
    {% block content %}{% endblock %}
    <footer>
        <p>&copy; 2023 DSWD FO XI</p>
    </footer>
</body>

</html>

kalahi_cidss/kalahi_cidss/templates/loading.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Loading...</title>
    <link rel="stylesheet" href="{% static 'css/loading.css' %}">
</head>
<body>
    <div class="loading-container">
        <div class="logo-container">
            <img src="{% static 'images/loading/kalahi_cidss_ncddp.png' %}" alt="Logo">
        </div>
    </div>
</body>
</html>